package ds.dfs.util;

public enum Command {
	CREATE, DELETE, OK, FAIL, DATANODE, NAMENODE, 
	DFSCLIENT, REGISTER, FILEDATA, FILETODFS, FILETONAMENODE,
	LISTFILES, PUTBLOCK, GETFILEDATA, FILETOLOCAL, GETFILEPARTS
}